### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [colsonc1/Week17#1]
I love the geolocation and the live Twitter feed! :tada: I do see a couple things I'd like updated though:
### Indentation

I see some inconsistent indentation and a lot of hard-tab indentation. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.
### Incomplete criteria

I see a couple cases where the criteria aren't _quite_ met. The unmet parts are bolded below:

> have a cats action in a StaticController served to /cat-pictures, which shows at least 1 cat picture, **then shows the number of cat pictures requested when visiting /cat-pictures/3 (for 3 cats) or /cat-pictures/5 (for 5 cats), for example**
> 
> have at least 1 helper method **that is used for some visible effect on at least 1 page**

---

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by colsonc1** [comment]
I'm just now seeing your review notes. Currently making the changes.

**Comment by colsonc1** [comment]
I do not understand this  criteria:
"have at least 1 helper method that is used for some visible effect on at least 1 page"
What is the first step I should take?

**Comment by chrisvfritz** [comment]
It looks like you have [a helper method defined here](https://github.com/colsonc1/Week17/blob/master/app/helpers/static_helper.rb), but it's not actually being _used_ anywhere in your views. Either in your layout or one of your views, try using the `current_date_and_time` helper that you created.

Let me know if that helps!

**Comment by colsonc1** [comment]
All Done

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
